### ISSUE TITLE
Suggestion: using zlib deflate dictionary to compress json data

### ISSUE THREAD

**Issue by link89** [rgcl/jsonpack#20]
Since zlib can use preset dictionary (http://www.zlib.org/rfc-zlib.html), we can make use of it for better json data compress.
The steps are:
1. travel object tree and found out most frequent terms (more than 10 times, for example)
2. set those term as deflate's preset dictionary 
3. JSON.stringify -> deflate(with preset dictionary) (-> base64, if binary is not acceptable)

The beauty of this solution is, it's a standard gzip + json compress method which can also rich same compress rate of jsonpack.

**Comment by rgcl** [comment]
Sounds nice, but also a lot of work (?)
