### ISSUE TITLE
Can not distinguish JSON string and JSON object

### ISSUE THREAD

**Issue by RnMss** [rgcl/jsonpack#21]
```
var data = { x: 1 };
var str = JSON.stringify(data);

jsonpack.unpack(jsonpack.pack( data ))
// returns an object { "x": 1234 }

jsonpack.unpack(jsonpack.pack( str ))
// returns an object { "x": 1234 }
// expected return value: a string  "{ \"x\": 1234 }"
```

**Comment by RnMss** [comment]
According to the defination, a JSON can be a string.
So a string that can be parsed into a JSON doesn't necessary mean a JSON presentation.

**Comment by rgcl** [comment]
Yep, it is a restriction of this library. We use a subsection of the JSON definition. For us, "{ x: 1 }" means { "x" : 1 }.

If this is important to you, you should check before using jsonpack, because jsonpack does not compress on a simple string.
